### ISSUE TITLE
upgrade skip control-plane when kubelet is not upgraded

### ISSUE THREAD

**Issue by pacoxu** [pacoxu/kubeadm-operator#74]
2 nodes cluster: server v1.22.10
- control-plane kubelet v1.21.10
- worker kubelet v1.21.10

```
apiVersion: operator.kubeadm.x-k8s.io/v1alpha1
kind: Operation
metadata:
  name: upgrade-v1.22.10
spec:
  executionMode: Auto
  upgrade:
    kubernetesVersion: v1.22.10
    local: false
```

### Current behavior
Upgrade runtime task generated
1.  upgrade worker

### Expected behavior
Upgrade runtime task generated
1.  upgrade control-plane: kubeadm upgrade node
1.  upgrade worker
